#' Watervolumes using files generated by Julias matlab script 
#' 
#' Intertidaal, subtidaal en geul wordt berekend (supratidaal wordt als gezien
#' als verwaarloosbaar). Geul wordt gedefinieerd als GLW-2. 

require(readr)
require(dplyr)
require(ggplot2)

Ageul_wlvariabel <- read.csv("~/MATLAB/Ageul_wlvariabel.csv", quote="")
Aintertidaal_wlvariabel <- read.csv("~/MATLAB/Aintertidaal_wlvariabel.csv", quote="")
Asubtidaal_wlvariabel <- read.csv("~/MATLAB/Asubtidaal_wlvariabel.csv", quote="")

Vgeul_wlvariabel <- read.csv("~/MATLAB/Vgeul_wlvariabel.csv", quote="")
Vintertidaal_wlvariabel <- read.csv("~/MATLAB/Vintertidaal_wlvariabel.csv", quote="")
Vsubtidaal_wlvariabel <- read.csv("~/MATLAB/Vsubtidaal_wlvariabel.csv", quote="")

Ageul_wlvariabel_long <- gather(Ageul_wlvariabel, 'Bekken', 'Oppervlakte', 'Balgzand':'Zwanenbalg.')
Ageul_wlvariabel_long$Gebied <- rep('Geul', nrow(Ageul_wlvariabel_long))

ggplot(aes(x=X.jaar, y=Oppervlakte, colour=Bekken,), data=Ageul_wlvariabel_long)+geom_point()+geom_line()+
  theme_bw()+ggtitle('Geulvolumes oppervlakte per bekken')+xlab('Jaar')+ylab('Oppervlakte [km2]')

Aintertidaal_wlvariabel_long <- gather(Aintertidaal_wlvariabel, 'Bekken', 'Oppervlakte', 'Balgzand':'Zwanenbalg.')
Aintertidaal_wlvariabel_long$Gebied <- rep('intertidaal', nrow(Aintertidaal_wlvariabel_long))

Asubtidaal_wlvariabel_long <- gather(Asubtidaal_wlvariabel, 'Bekken', 'Oppervlakte', 'Balgzand':'Zwanenbalg.')
Asubtidaal_wlvariabel_long$Gebied <- rep('subtidaal', nrow(Asubtidaal_wlvariabel_long))
#' Arealen 
#' 
A_wlvariabel <- rbind(Aintertidaal_wlvariabel_long, Asubtidaal_wlvariabel_long, Ageul_wlvariabel_long)
A_wlvariabel[A_wlvariabel == 'Zwanenbalg.'] <- 'Zwanenbalg'

Bekkens <- unique(A_wlvariabel$Bekken)

plots_list <- list()
for (i in 1:length(Bekkens)) {
  plots_list[[i]] <- ggplot(aes(x = X.jaar, y = Oppervlakte, pch = Gebied, colour= Gebied), 
                            data = A_wlvariabel %>% filter(Bekken == Bekkens[i])) +
    geom_point() + geom_line() + theme_bw() +
    ggtitle(paste('Arealen', Bekkens[i]))+
    ylab('Oppervlakte (km2)')+ xlab('Jaar')
}

plots_list[1:6]


