# Vogels

```{r setupZeeZoogdieren, include = FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)
require(sf)
require(leaflet)
require(tidyverse)
```


```{r, child="_40_vogels/_zeetrektellingen_noordzeekustzone.Rmd"}
```

```{r, child="_40_vogels/_aantallen_en_verspreiding_pleisterende_watervogels_in_de_waddenzee.Rmd"}
```

```{r, child="_40_vogels/_aantallen_en_verspreiding_pleisterende_wad_en_watervogels_in_de_waddenzee.Rmd"}
```

```{r, child="_40_vogels/_aantallen_watervogels_in_de_waddenzee_op_basis_van_boottellingen_.Rmd"}
```

```{r, child="_40_vogels/_aantallen_watervogels_in_de_waddenzee_vliegtuigtellingen_.Rmd"}
```

```{r, child="_40_vogels/_aantallen_broedende_wad_en_watervogels_langs_waddenzee_en_noordzeekustzone.Rmd"}
```

```{r, child="_40_vogels/_broedsucces_van_wad_en_watervogels_in_waddenzee_en_noordzeekustzone.Rmd"}
```

```{r, child="_40_vogels/_aantallen_ganzen_en_zwanen_wz_delta_kustgebieden_.Rmd"}
```

```{r, child="_40_vogels/_monitoring_zeevogels_noordzee_vliegtuigtellingen_.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_aalscholver.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_blauwe_kiekendief.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_grote_stern.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_monitoring_kanoet.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_monitoring_rosse_grutto.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_lepelaar.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_rotgans.Rmd"}
```

```{r, child="_40_vogels/_verspreiding_en_overleving_individuele_broed_en_trekvogels.Rmd"}
```

```{r, child="_40_vogels/_ringonderzoek_aan_wadvogels_in_getijdengebieden.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_scholekster.Rmd"}
```

```{r, child="_40_vogels/_meetnet_nestkaarten.Rmd"}
```

```{r, child="_40_vogels/_ptt_punt_transect_tellingen.Rmd"}
```

```{r, child="_40_vogels/_ces_project.Rmd"}
```

```{r, child="_40_vogels/_meetnet_slaapplaatsen.Rmd"}
```

```{r, child="_40_vogels/_vogel_en_zoogdiersterfte.Rmd"}
```

```{r, child="_40_vogels/_wadplaattellingen_waddenunit_ez.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_drieteenstrandloper.Rmd"}
```

```{r, child="_40_vogels/_populatiestudie_kleine_mantelmeeuw.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_zilvermeeuw.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_tureluur.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_steenloper.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_kluut.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_visdief.Rmd"}
```

```{r, child="_40_vogels/_populatiestudies_noordse_stern.Rmd"}
```