
# Waterkwantiteit

```{r setupWaterkwaliteit, include = FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	echo = FALSE
)
require(sf)
require(leaflet)
require(tidyverse)
source("r/runThisFirst.R")
```

1.3	Afvoeren
De zoetwaterafvoer wordt opgenomen als indicator omdat het de saliniteit en de waterbeweging beïnvloedt. De data van de grootste afvoeren (Den Oever, Kornwerderzand, Lauwersoog) zijn goed ontsloten en worden als indicator opgenomen. Andere/kleinere afvoeren zijn zeer nuttig om te ontsluiten, maar deze gegevens zijn via de waterschappen zeer moeilijk te verkrijgen. Bovendien is de verwachting dat de kleinere afvoeren de eventuele trends in de grotere afvoeren (als gevolg van toegenomen regenval) zullen volgen. De afvoeren bij Den Oever en Kornwerderzand worden beïnvloed door het peilbeheer in het IJsselmeer. Daarom worden ook zomer- en wintergemiddelde afvoeren gevizualiseerd.

Analyse(s)/figuren:
1.	Jaargemiddelde afvoer
2.	Zomer- en wintergemiddelde

Brondata: afvoergegevens (LMW?) in het Waddengebied

 
1.4	Wind
Wind wordt opgenomen als indicator omdat waterbeweging in de Waddenzee erg gevoelig is voor windgedreven stroming door de ondiepe ligging en grote strijklengtes. Windstatistieken geven inzicht in hoe dynamisch een bepaald jaar was en of er lange termijn veranderingen optreden.

Analyse(s)/figuren:
1.	25, 50, 75 en 95-percentiel van de windsnelheid per jaar
2.	Duur (uren) dat windsnelheid > 7 m/s (en/of andere grenzen) 
Duur (uren) dat windsnelheid > 7 m/s uitgesplitst naar de 4 kwadranten: NO, ZO, ZW, NW 

Brondata: 4 KNMI windstations in het Waddengebied


1.5	Golfhoogte
De golfhoogtes geven ook inzicht in de dynamiek van de verschillende jaren. 

Analyse(s)/figuren:
1.	95-percentiel van de significante golfhoogte per jaar
2.	Afwijking maandgemiddeld t.o.v. langjarig gemiddelde, als maat voor seizoensdynamiek. Verschillende jaren weergeven als lijnen met kleurverloop (oude jaren blauw en naar heden toe verkleurend naar rood) 

Brondata: Golfboeien in de Noordzee en Waddenzee. Of de boeien in de Waddenzee ook echt operationeel zijn is twijfelachtig…

 

1.6	Golfperiode (extra toegevoegd)
De golfperiodes geven ook inzicht in de dynamiek van de verschillende jaren. 

Analyse(s)/figuren:
1.	95-percentiel van de golfperiode Tm02 per jaar, incl metingen als losse puntjes

Brondata: Golfboeien in de Noordzee en Waddenzee. Of de boeien in de Waddenzee ook echt operationeel zijn is twijfelachtig…

 

1.7	Waterhoogte bij storm
Waterstanden tijdens events geven inzicht hoeveel en hoe krachtige stormen er zijn opgetreden per jaar. Er worden 2 parameters opgenomen als indicator: de stormopzet (excl. getij) en de stormvloedhoogte (incl. getij). De laatste geeft ook de afhankelijkheid weer van het moment in de getijfase dat een storm optreedt.

Analyse(s)/figuren:
1.	Opzet/afzet = gemeten waterstand - astronomische waterstand. Weergeven: tijdreeks of 95-percentiel
2.	Stormhoogte = gemeten waterstand: 95-percentiel per jaar. 

Brondata: ~23 waterstandstations in het Waddengebied en de Noordzeekustzone van LMW. 
1.8	Zeespiegelstijging
Hier wordt de jaargemiddelde waterstand weergegeven en verwezen naar de zeespiegelstijgingsmonitor voor de uitgebreidere analyses en benodigde correcties. 

Analyse(s)/figuren:
1.	Jaargemiddelde waterstand en 19-jarig lopend gemiddelde om te verdisconteren voor de 18,6 jarige cyclus.

Brondata: ~23 waterstandstations in het Waddengebied en de Noordzeekustzone van LMW. 

 
 

1.9	GLW, GHW en getijslag
De Gemiddelde Hoog Water en Gemiddelde Laag Water niveaus zijn relevant voor de ecologie en samen met de getijslag ook voor de morfologische ontwikkeling. Voor deze analyse moeten eerst alle hoog- en laagwaters per station worden bepaald op basis van de gemeten waterstand. Let op, voor oudere jaren werd in het verleden maar eens per uur gemeten en HW en LW separaat geregistreerd. Uiteraard moet er dan gemiddeld worden over deze HW en LW standen.

Analyse(s)/figuren:
1.	Jaargemiddelde GLW en 19-jarig lopend gemiddelde om te verdisconteren voor de 18,6 jarige cyclus.
2.	Jaargemiddelde GHW en 19-jarig lopend gemiddelde om te verdisconteren voor de 18,6 jarige cyclus.
3.	Jaargemiddelde getijslag (GHW-GLW) en 19-jarig lopend gemiddelde om te verdisconteren voor de 18,6 jarige cyclus.
4.	Kaart met getijslag van het meest actuele jaar om verloop in de Waddenzee te laten zien.

Brondata: ~23 waterstandstations in het Waddengebied en de Noordzeekustzone van LMW. 

 
 
 
 
1.10	GLLWS & GHHWS
Gemiddeld Laag Laagwater Spring en Gemiddeld Hoog Hoogwater Spring zijn van belang voor de ecologie? En worden daarom hierbij opgenomen. Veranderingen hierin kunnen gekoppeld worden aan veranderingen in de getijcomponenten. De springtij-doodtij cyclus ontstaat door interactie van de M2 en S2 getijcomponent, die opgenomen zijn in de volgende paragraaf.

Analyse(s)/figuren:
1.	GLLWS: gemiddelde van de laagste waterstand per maand over een periode van 5 jaar. Op basis van astronomische waterstand
2.	GHHWS: gemiddelde van de hoogste waterstand per maand over een periode van 5 jaar. Op basis van astronomische waterstand

Brondata: ~23 waterstandstations in het Waddengebied en de Noordzeekustzone van LMW. 

1.11	Getijcomponenten en -asymmetrie (extra toegevoegd)
De M2 component van het getij heeft de grootste amplitude en ontstaat door aantrekkingskracht van de maan. De S2 component wordt veroorzaakt door de aantrekkingskracht van de zon en vormt met de M2 component de springtij-doodtij cyclus. De M4 component is een hogere harmonische component en een ondiepwatereffect van M2 (i.e. harmonische boventoon / veelvoud van M2). Ondiepwatereffecten ontstaat doordat de getijgolf sneller voorplant in hoogwater dan in laagwater

De M4/M2 amplitudeverhouding en het relatief faseverschil 2M2-M4 kunnen worden gebruikt voor de kwantificatie van de getijasymmetrie die belangrijk is voor het netto sedimenttransport (Friedrichs en Aubrery, 1988). Het relatief faseverschil bepaalt de aard van de asymmetrie: de pieksnelheid is vloeddominant als het tussen 0 en 180 graden is en ebdominant als het tussen 180 en 360 graden is. De grootte van de amplitudeverhouding is een indicator voor de sterkte van de asymmetrie.

Analyse(s)/figuren:
1.	Tijdreeks van de amplitude M2 per jaar voor de verschillende stations en 19-jarig gemiddelde
2.	Tijdreeks van de amplitude S2 per jaar voor de verschillende stations en 19-jarig gemiddelde
3.	Tijdreeks van de amplitude M4 per jaar voor de verschillende stations en 19-jarig gemiddelde
4.	Tijdreeks van de amplitudeverhouding M4/M2 per jaar voor de verschillende stations en 19-jarig gemiddelde
5.	Tijdreeks van het relatieve faseverschil 2phiM2-phiM4 per jaar voor de verschillende stations en 19-jarig gemiddelde

Brondata: ~23 waterstandstations in het Waddengebied en de Noordzeekustzone van LMW. 

 

