
\newpage

# Informatiebehoefte {#Informatiebehoefte}

```{r, message=FALSE, warning=FALSE, include=FALSE}


```

De doelen van de Basismonitoring zijn de hoofdstuk \@ref(introductie) al benoemd. Deze digitale systeemrapportage bevat tot nu toe de belangrijkste continue monitoringsdata. Met het uitwerken van de indicatoren is ook gereflecteerd welke aanvullende metingen er gedaan zouden moeten worden om de trends en toestand in de Waddenzee beter te kunnen volgen en het systeembegrip te vergroten. Ook is er zicht op bestaande monitoring, die nog niet goed ontsloten is. In dit hoofdstuk wordt er nader ingegaan op deze metingen. Besluitvorming over wat er daadwerkelijk gemeten gaat worden, door wie, en welke kosten daar aan verbonden zijn, is een volgende stap in het proces van het invullen van een effectieve morfologische monitoring. Daarbij dient ook opgemerkt te worden dat hier alleen de abiotische monitoring behandeld wordt, en niet ook de biotische, terwijl deze voor het verbeteren van systeemkennis en het evalueren van beleidsdoelen juist in samenhang beschouwd moeten worden.

## Nieuwe metingen
Deze paragraaf beschrijft de belangrijkste nieuwe metingen die geinventariseerd zijn. Een volledig overzicht is opgenomen in de Deltares memo Meet- en monitoringbehoefte [download](https://publicwiki.deltares.nl/download/attachments/137135283/11208040-003-ZKS-0001_v0.3-Meet-%20en%20monitoringbehoefte_dec.pdf?version=1&modificationDate=1678353584330&api=v2).

**Getijvolumes**
De debieten door de zeegaten en over de wantijen zijn van belang om uitwisseling met de Noordzee en tussen de kombergingsgebieden onderling te kunnen kwantificeren. De laatste bekende reeks 13-uurs metingen in de zeegaten dateert van 2005 en is niet digitaal ontsloten. Sindsdien is er veel veranderd door geulmigratie en veranderingen in kombergingsvolume. Idealiter wordt in alle zeegaten een 13-uurs meting om de volumebalans en de uitwisseling tussen zeegaten in beeld te brengen, die elke 6-12 jaar (aansluitend op de frequentie van de vaklodingen en daaruit af te leiden sedimentbalansen) per zeegat herhaald wordt om aan te sluiten bij de tijdschaal waarop morfologische veranderingen plaatsvinden.

**Saliniteit**
Er zijn metingen van saliniteit in de Waddenzee (in het meetnet van de MWTL), maar deze hebben een hele grove temporele resolutie. Ook de de ruimte is de dekking beperkt. Toch is het waardevol om goed inzicht te krijgen in de saliniteitsverdeling in de Waddenzee. Voor de ecologie is het direct van belang, omdat soorten alleen kunnen overleven binnen een bepaalde saliniteitsrange. Bij over- of onderschrijding daarvan, hangt het van de duur daarvan af wat de impact is. De saliniteitsverdeling heeft ook invloed op de slibdynamiek, omdat de gravitatiecirculatie ervoor zorgt dat slib effectief in de Waddenzee naar binnen wordt getransporteerd. Ook geven metingen van de saliniteit inzicht in de uitwisseling van water over de wantijen. De enorme zoetwaterbel die voor de Afsluitdijk ligt, kan onder bepaalde windcondities ver verplaatsen, zo laten projectmetingen in het Amelander Zeegat bijvoorbeeld zien (binnen het SEAWAD project). Remote sensing (gekalibreerd op metingen) kan mogelijk worden ingezet om aanvullende informatie over de saliniteitsverdeling te vergaren.

het is raadzaam om hoogfrequente metingen van saliniteit (en daarmee ook van de watertemperatuur) uit te voeren in geulen en op platen, om zo een beter beeld te krijgen in de temporele en ruimtelijke verdeling. 

**Slibconentraties, zwevende stof**
Zwevende stof wordt alleen structureel binnen het MWTL (maandelijks tot tweewekelijks) bemeten, waardoor de temporele resolutie beperkt is. De consistente inwinning van de data sinds 1989 laten een trendanalyse toe, maar er is weinig inzicht in de variatie binnen het getij en het effect van stormen. Binnen het project KRW slib is er advies gegeven over het additioneel inwinnen van zwevende stof data. Het betreffende advies bestaat uit twee memo's die elk kunnen worden gedownload van de publicwiki van Deltares: [Voorstel nieuwe metingen slibhuishouding Waddenzee](https://publicwiki.deltares.nl/download/attachments/137135283/BG2802-RHD-ZZ-XX-NT-Z-0001_voorstel%20nieuwe%20metingen_versie%203a.pdf?version=1&modificationDate=1580229139728&api=v2) en [Voorstel nieuwe meting zwevendstof Dantziggat](https://publicwiki.deltares.nl/download/attachments/137135283/Voorstel_nieuwe_meting_zwevend_stof_Dantziggat_9maart2020.pdf?version=1&modificationDate=1607942275465&api=v2).

Ook de samenstelling van sediment in de waterkolom is een inzichtelijke parameter voor de slibdynamiek. In de [Wadden In Beeld rapportage](https://www.waddenzee.nl/fileadmin/content/Dossiers/Overheid/waddenzeebeheer/WIB-2019-webversie-met_hyperlinks_7.pdf) staat deze dan ook opgenomen onder de meetbehoefte. 

Een aanvullende meetbehoefte betreft de baggervolumes. Door de bodemsamenstelling in de baggervakken te monitoren, kan beter inzicht verkregen worden in de samenstelling van het verspreidde materiaal, en daarmee het effect op het morfologisch-ecologisch systeem.

## Data-ontsluiting {#ontsluiting}
Ook wat betreft de data-ontsluiting zijn er verbeterpunten. Zeker bij het werken met digitale systeemrapportages loont het om de data-ontsluiting goed op orde te hebben, zodat de rapportage gemakkelijker kan worden geupdate als nieuwe data beschikbaar komen. De scripting achter de rapportage is in elk geval zo opgesteld, dat dit mogelijk is. Desalniettemin heeft het verzamelen van de data meer tijd gekost omdat niet alles goed ontsloten is. Onderstaand lijstje geeft een overzicht van gegevens, die beter ontsloten zouden moeten worden:

- Waterstanden
+ Oude waterstandsgegevens (voor 1986) zitten niet in de Data Distributie Laag en zijn los opgevraagd en /of ingelezen van de Open Earth DataServer. 
+ De gerapporteerde hoogwaters (HW) en laagwaters (LW) zijn vooral van belang voor de periode voor 1966, toen 3-uurlijkse waterstanden werden gerapporteerd. Dit is een te grove temporele resolutie om te gebruiken voor analyses. HW en LW data zitten niet in de Data Distributie Laag en zijn los opgevraagd. 
+ De waterstanden op de stations AWG platform, Den Oever buiten, Kornwerderzand buiten, Nieuwe Statenzijl, Oudeschild, Termuntenzijl en Vlieland haven zitten niet in de Data Distributie Laag. De reden hiervoor is niet bekend, maar het is wel waardevol deze data alsnog te ontsluiten, zodat ze in de rapportage kunnen worden opgenomen.
+ De getijcomponenten zijn niet beschikbaar. Binnen project Kenmerkende Waarden Kust (Deltares referentie 11205235) is in opdracht van Rijkswaterstaat een Python toolbox ("hatyan") ontwikkeld om deze componenten uit te rekenen voor ondiepe gebieden als de Waddenzee. Deze berekeningen zijn gekoppeld aan deze digitale rapportage, waarmee het afleiden van de getijcomponenten reproduceerbaar is geworden. Ook worden daarmee dezelfde componenten in de verschillende studies gebruikt. Wij bevelen aan deze werkwijze/Python toolbox verder te formaliseren.
- Gegevens van de middelgrote en kleinere zoetwatervoeren in de Waddenzee zijn niet ontsloten en vaak ook niet beschikbaar. Ze kunnen afgeleid worden op basis van het verval over het betreffende spuimiddel. Deze spuimiddelen zijn in beheer van de waterschappen.
- Bagger- en verspreidingsvolumes. Aanbevolen wordt om alle baggerhoeveelheden uit te drukken in in-situ volumes in m3 en in TDS (tonnen droge stof). In-situ volumes zijn belangrijk voor de morfologische effecten en TDS is belangrijk voor ecologische effecten zoals vertroebeling en beter geschikt voor vergelijking met slibtransport modellen. Er wordt binnen Rijkswaterstaat gewerkt aan een consistente manier van het registreren en rapporteren van de bagger- en verspreidingsvolumes. Deze data dient digitaal ontsloten te worden, waarna deze gelinkt kan worden aan deze systeemrapportage.
- Er zijn verschillende projectmetingen beschikbaar, die waardevol zouden zijn om goed te ontsluiten. Het memo Meet- en monitoringbehoefte [download](https://publicwiki.deltares.nl/download/attachments/137135283/11208040-003-ZKS-0001_v0.3-Meet-%20en%20monitoringbehoefte_dec.pdf?version=1&modificationDate=1678353584330&api=v2) geeft hiervan een overzicht.

Voor de ontsluiten van data wordt vanuit dit project Natuurmonitoring de samenwerking gezocht met Datahuis Wadden.

<!--  misschien wel leuk, we hebben vorig jaar met DCSM ook naar een proxy voor sedimenttransport gekeken (als extraatje in de studie, dus verwacht daarover niet al te veel diepgang):
n:\Projects\11205000\11205235\F. Other information\014-getijde-energie\Effect van SLR op getij Nederlandse kust definitief.pdf -->

