---
title: "Test inlezen dia files met HATYAN"
author: "Willem Stolte"
date: "5/11/2022"
output: html_document
---

## Set up Conda environment

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(reticulate)
source("r/runThisFirst.R")

py_install("pandas")

conda_list()
conda_create(envname = "kenwaar_conda", packages = c("numpy", "matplotlib==3.2.1"))
use_condaenv("kenwaar_conda")
py_install("hatyan", pip = T)
# reticulate::py_run_file("hatyanExample.py")


filenames <- c(
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/eemshaven.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/harlingen.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/holwerd.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/huibertgat.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/lauwersoog.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/nes.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/schiermon.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/terschel.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/texel.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/westter.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/wierumerg.dia",
  "p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/denhelder.dia"
  )

```


## Read Dia file using hatyan package

```{python  init, echo = T, include = F}
import datetime as dt
import pandas as pd
import hatyan
hatyan.close('all')

```
  

Voor opname in de systeemrapportage worden de dia files omgezet naar csv.   

```{python include=FALSE}
import pandas as pd
import datetime as dt #of date
import hatyan
import numpy as np
import os

dir = r"p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/"
# save = 'C:\\projecten\\rws\\2022\\scripts\\'
save = 'p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/'

# iterating over all files

for files in os.listdir(dir):
    if files.endswith('.dia'): #search for files in folder with the dia extension
        diablocks_pd = hatyan.get_diablocks(dir + files)
        stat_code = diablocks_pd['station'].unique()[0] #this assumes there is only one station in the file, since it uses the first unique station
        data = hatyan.readts_dia(filename=dir +files, station=stat_code, block_ids="allstation", get_status = True)
        data = data.reset_index(drop=False) # tijd index als kolom maken
        new_name = files.replace (".dia", ".csv") #change extension
        data.to_csv(save + new_name, sep=';') #edit to save as csv
    else:
        continue
```


```{python  readDia, echo = T, include = F}

  file_data = r"p:/11202493--systeemrap-grevelingen/1_data/Wadden/RWS/hoogLaagWaters/harlingen.dia"
  diablocks_pd = hatyan.get_diablocks(file_data)
  stat_code = diablocks_pd['station'].unique()[0] #this assumes there is only one station in the file, since it uses the first unique station
  data = hatyan.readts_dia(filename=file_data, station=stat_code, block_ids="allstation", get_status = True)
  
  data = data.reset_index(drop=False) # tijd index als kolom maken
```
  
```{r checkDia}
str(py$data)
```



```{r plotDia}
py$data %>%
  mutate(HWLWcode = as.factor(HWLWcode)) %>%
  ggplot(aes(times, values)) +
  geom_point(aes(color = Status), alpha = 0.2) +
  facet_grid(. ~ HWLWcode)
```





